version: "3.9"
services:
  liquidsoap:
    image: savonet/liquidsoap:rolling-release-v2.1.x #savonet/liquidsoap:rolling-release-v2.0.x
    container_name: liquidsoap
    restart: always
    command: ["/etc/liquidsoap/script.liq"]
    #depends_on:
    # - icecast
    volumes:
      - '$PWD/config:/etc/liquidsoap'
      - '$PWD/audio:/var/audio':ro
    environment:
      - PROMETHEUS_ENABLED
      - SOURCE_PASSWORD
      - SOURCE_TYPE
      - SOURCE_PORT
      - ICECAST_SERVER_ADDRESS
      - ICECAST_SERVER_PORT
      - ICECAST_SERVER_PASSWORD
      - ICECAST_STL_ENABLED
      - ICECAST_STL_NAME
      - ICECAST_STL_DESC
      - ICECAST_STL_MOUNTPOINT
      - ICECAST_HQ_ENABLED
      - ICECAST_HQ_NAME
      - ICECAST_HQ_DESC
      - ICECAST_HQ_MOUNTPOINT
      - ICECAST_LQ_ENABLED
      - ICECAST_LQ_NAME
      - ICECAST_LQ_DESC
      - ICECAST_LQ_MOUNTPOINT
      - STEREOTOOL_ENABLED
      - STEREOTOOL_PORT
      - FALLBACK_FILE
    ports:
      - "${SOURCE_PORT}:${SOURCE_PORT}"
      - "${STEREOTOOL_PORT}:${STEREOTOOL_PORT}"
      - "9090:9090"
